from functools import cache
from colorama import Fore, Back, Style


def main(data):
    print(f"The value generated by the notes is {find_either_mirror(data, True)}.")
    return


def find_either_mirror(mirror_map, check_smudges=False):
    result = 0
    temp_map = []
    map_num = 1
    for line in mirror_map:
        if line == "":
            print()
            print(f"Map #{map_num}")
            result += locate_mirror(temp_map, check_smudges)
            temp_map = []
            map_num += 1
        else:
            temp_map.append(line)
    print()
    print(f"Map #{map_num}")
    result += locate_mirror(temp_map, check_smudges)
    return result


def locate_mirror(temp_map, check_smudges):
    mirror_location = find_individual_mirror(temp_map, check_smudges)
    if mirror_location > -1:
        print_map(temp_map, mirror_location)
        print()
        print(f"{mirror_location}: {mirror_location * 100} points")
        return mirror_location * 100
    rotated_map = rotate_map(temp_map)
    mirror_location = find_individual_mirror(rotated_map, check_smudges)
    if mirror_location > -1:
        print_map(temp_map,-1,mirror_location)
        print()
        print(f"{mirror_location}: {mirror_location} points")
        return mirror_location
    return 0


def print_map(map_data, row=-1, col=-1):
    for x, line in enumerate(map_data):
        for char in line:
            print(Back.BLACK + " ", end="")
            if char == "#":
                print(Fore.LIGHTGREEN_EX, end="")
            else:
                print(Fore.LIGHTRED_EX, end="")
            print("█", end="")
        print(" ", end="")
        print(Style.RESET_ALL, end="")
        print(str(x + 1).rjust(2, " "), end="")
        if (row - 1) == x:
            print("v")
        elif (row) == x:
            print("^")
        else:
            print()
    for y in range(len(map_data[0])):
        print(str(y + 1).rjust(2, " "), end="")
    if col < 0:
        return
    temp = ""
    print()
    for y in range(len(map_data[0])):
        if y == col - 1:
            temp += " >"
        elif y == col:
            temp += "< "
        else:
            temp += "  "
    print(temp)


def find_individual_mirror(mirror_map, check_smudges):
    temp = []
    result = -1
    for idx, line in enumerate(mirror_map):
        temp.append(line)
        if check_if_mirror(mirror_map, temp, idx, check_smudges):
            result = idx + 1
            break
    return result


def check_if_mirror(main_map, temp, idx, check_smudges):
    result = False
    starting_idx = int(idx)
    for temp_idx, line in enumerate(reversed(temp)):
        mirror_idx = starting_idx + 1 + temp_idx
        if mirror_idx >= len(main_map):
            return result
        if temp[idx] == main_map[mirror_idx]:
            result = True
            idx -= 1
        elif check_smudges and abs(temp[idx].count("#") - main_map[mirror_idx].count("#")) == 1:
            smudged = check_for_smudge(temp[idx], main_map[mirror_idx])
            if smudged:
                result = True
                idx -= 1
            else:
                return False
        else:
            return False
    return result


@cache
def check_for_smudge(string1, string2):
    for idx, char in enumerate(string1):
        if char == "#":
            temp_string = string1[:idx] + "." + string1[idx + 1:]
        else:
            temp_string = string1[:idx] + "#" + string1[idx + 1:]
        if temp_string == string2:
            return True
    return False


def rotate_map(mirror_map):
    result = []
    map_tuple = (zip(*mirror_map[::1]))
    for line in map_tuple:
        temp = ""
        for item in line:
            temp += item
        result.append(temp)
    return result
